### ISSUE TITLE
Hi, we noticed that Matecat alters .ttx file's header. Is it possible to prevent that? 

### ISSUE THREAD

**Issue by wsuphappyhour** [matecat/MateCat-Filters#15]
Hi, we noticed that Matecat alters .ttx file's header. Is it possible to prevent that? 

Original on the left side.
![image](https://cloud.githubusercontent.com/assets/20355306/19232992/7d419fda-8eeb-11e6-8b02-905b14db6d3d.png)
[Changes.zip](https://github.com/ModernMT/MMT/files/519276/Changes.zip)

Thanks!

**Comment by giusilvano** [comment]
Hi! The example you sent shows an alteration indeed, but it's just in the _representation_ of the content, the content itself (tags structure, tags contents and attributes) is not changed. The two representation are perfectly equivalent in XML language. For this reason we haven't found any compatibility issues so far, so we consider this issue low priority.

**Comment by giusilvano** [comment]
I close the issue for inactivity, but feel free to continue the conversation if something is unclear.
