### ISSUE TITLE
Hi, we noticed that matecat.com changes &gt; to > and xliff file can't be opened with Translation Workspace. 

### ISSUE THREAD

**Issue by wsuphappyhour** [matecat/MateCat-Filters#16]
Hi, we noticed that MateCat.com changes &gt; to > within tag and xliff file can't be opened with Translation Workspace. 
We tested this on our instance as well as original MateCat.com outcome is the same. 
Original on the left, MateCat output on the right
![image](https://cloud.githubusercontent.com/assets/20355306/19433782/cf982b76-946a-11e6-8b8b-4e095d8ab6ab.png)
![image](https://cloud.githubusercontent.com/assets/20355306/19433822/fb0dcdba-946a-11e6-9ec6-d918e36355d6.png)
If you need both files or MateCaT url, let me know.
Thanks!

**Comment by giusilvano** [comment]
Hi @wsuphappyhour, thank you for reporting this! I think we will soon push a commit to address this issue, I'll keep you updated.

**Comment by giusilvano** [comment]
I just pushed a commit in the dev branch to address this issue, now it is solved! Can you confirm it please?

**Comment by giusilvano** [comment]
I close the issue for inactivity, but please let me know if the fix we made solved your problem!
