### ISSUE TITLE
What's the difference between /AutomationService/xliff2original and /AutomationService/xliff2source resources?

### ISSUE THREAD

**Issue by LLCampos** [matecat/MateCat-Filters#2]
The documentation doesn't explain the difference. 

The code is also confusing. In the _GenerateDerivedFileResource_ file, which corresponds to the resource /AutomationService/xliff2source it is written that this resource takes "care of the extraction of the **original** file from the .XLF".

On the other hand, in the _Extract**Original**FileResource_ file, which corresponds to the resource /AutomationService/xliff2**original** it is written that the resource takes "care of the generation of the new file from the .XLF".

So, the /AutomationService/xliff2original **does not** return the original file? That's not really intuitive.

**Comment by giusilvano** [comment]
Hi LLCampos,

Sorry again for the late reply.
You are right. The API design is a bit confusing and can be improved a lot.
The current API is heritage of the old filters infrastructure we wrote in the early days of MateCat.
Now that the new Filters are solid we are starting to rethink the REST communication layer, we plan to replace it in the next releases.

This is what the two endpoints currently do:
* **xliff2original** takes an XLIFF file and returns a file in the original format with all the translations in place;
* **xliff2source** takes an XLIFF file and returns the original source file used to generate it.

I promise it will be more intuitive in future. It's just a matter of time and budget. :)
