### ISSUE TITLE
Error 7

### ISSUE THREAD

**Issue by HURIMOZ** [matecat/MateCat-Filters#21]
Services stop after a while, I get an error 7 message and can no longer upload any file..

**Comment by LLCampos** [comment]
Can you provide more information? I've used MateCat-Filters a lot and that never happened.

**Comment by giusilvano** [comment]
@HURIMOZ I close the issue for inactivity, but feel free to add details if something else comes up.
Thank you @LLCampos for the additional support! :D
Anyway, we are close to releasing an update, if we are lucky enough this _error 7_ will be already fixed.
