### ISSUE TITLE
source/target language not correctly tagged in original2xliff result

### ISSUE THREAD

**Issue by Junqing** [matecat/MateCat-Filters#25]
It seems the logs are showing that the language combination are correctly received: 

[CONVERSION REQUEST] xxxx.xlsx: en-US to da-DK
[PROJECT CREATED] Norwegian Translations.xlsx saved in /tmp/2092361387035352077
Using default segmentation
Input: /tmp/2092361387035352077/xxxxxlsx
[CONVERSION FINISHED] xxxx.xlsx: en-US to da-DK

However in the xliff file the source and target tags are incorrectly tagged (always) as source="en" and target="fr"

Any ideas?

**Comment by giusilvano** [comment]
Unfortunately, this was a bug in the 1.2.2 version, but we already fixed it in the 1.2.3. 
Can you update your code and confirm me that the bug has gone?

**Comment by giusilvano** [comment]
Since the bug should be solved I close the issue. Feel free to re-open it or add any further info you think useful. Thanks!
