### ISSUE TITLE
PDF file  " No registered filter supports the source file "

### ISSUE THREAD

**Issue by 959210490** [matecat/MateCat-Filters#26]
I find the OkapiFilterFactory.java ,see it is not support the pdf ，but i find the readme.md it say that support the pdf

**Comment by giusilvano** [comment]
Hi! Filters can automate the conversion of PDFs using an additional component, [MateCat Win Converter](https://github.com/matecat/MateCat-Win-Converter), and an external service. The wiki about [supported formats](https://github.com/matecat/MateCat-Filters/wiki/Supported-file-formats#formats-supported-using-matecat-win-converter) has some handy info about this. Let me know if everything is not clear.
