### ISSUE TITLE
Failed tests

### ISSUE THREAD

**Issue by LLCampos** [matecat/MateCat-Filters#3]
Hi,
When I run the tests on this project there are some failures. 

```
Results :

Failed tests: 
  ExtractOriginalFileResourceTest.testOriginalSuccess:53 expected:<200> but was:<500>
  GenerateDerivedFileResourceTest.testDeriveSuccess:55 expected:<200> but was:<500>
  ConvertToXliffResourceTest.testConvertSuccess:58 expected:<200> but was:<500>

Tests in error: 
  XliffProcessorTest.testGetOriginalFile:26 » ExceptionInInitializer
  XliffProcessorTest.testGetDerivedFile:47 » NoClassDefFound Could not initializ (..)
 (...)

Tests run: 53, Failures: 3, Errors: 29, Skipped: 0
```

But everything seems ok when testing manually: I can turn the server on and make requests to it. 

(I'm new to Maven so I could be doing something wrong)

**Comment by giusilvano** [comment]
Hi LLCampos,

Sorry for the late response. Anyway I can't reproduce your issue. 

Have you already solved it somehow or you are still experiencing it?

**Comment by giusilvano** [comment]
Dear LLCampos,

I close the issue due to inactivity, but feel free to reply me if you still need help with this.

Thank you!

**Comment by LLCampos** [comment]
Probably I'm doing something wrong. I know zero about Maven. But thanks!
