### ISSUE TITLE
Error parsing the DTD

### ISSUE THREAD

**Issue by LLCampos** [matecat/MateCat-Filters#8]
Hello, 

In the Wiki it is written that Filters supports DTD, but when I try to convert some examples to XLIFF I get an error "Error parsing the DTD". [The examples I've used](http://www.w3schools.com/xml/xml_dtd_examples.asp).

LLCampos :)

**Comment by giusilvano** [comment]
The DTDs are processed using [this filter](http://okapiframework.org/wiki/index.php?title=DTD_Filter) of Okapi. The documentation says that the filter is suited for DTDs containing just entities definition, while unfortunately the doctype definition (contained in your example files) seems not supported. I'm sorry about that!
